apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-chart.fullname" . }}
  labels:
    {{- include "todo-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todo-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "amul047/updatesapi:latest"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
        - name: {{ .Chart.Name }}-workerservice
          image: "amul047/todoworkerservice:latest"
          
